#!/usr/bin/env bash
set -e

jupyter serverextension enable jupyter_server_proxy
jupyter nbextension install --py jupyter_server_proxy
jupyter nbextension enable --py jupyter_server_proxy
jupyter labextension install @jupyterlab/server-proxy

echo auth-none=1 >> /etc/rstudio/rserver.conf
echo auth-minimum-user-id=0 >> /etc/rstudio/rserver.conf
